name: Build and deploy Node.js app to Azure Web App - sttp-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        working-directory: ./Frontend  # Set the working directory to the 'Frontend' folder
        run: |
          npm install
          npm run build  # Build the React app to generate production-ready files

      - name: Upload build artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./Frontend/build  # Upload the build folder after running 'npm run build'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Download build artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8B84359273ED444AB505824E8B73EBA5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_44433E5D9DDF42C4B45F26C571B983FA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9922D9CAFEF1433EBC4E8EC9D9257A77 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sttp-webapp'
          slot-name: 'Production'
          package: './Frontend/build'  # Deploy the contents of the build folder
